[project]
name = "virtual-stream-utility"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "p4python>=2025.1.2767466",
    "pyside6>=6.9.0",
]


[dependency-groups]
dev = [
    "nuitka>=2.7.5",
]
